import csv
from pathlib import Path

columns = [
    "stadium_id",
    "stadium_name",
    "capacity",
    "address",
    "year_of_construction",
    "owner_raw",
    "ownership",
    "stadium_type",
    "surface",
    "architect",
    "wikipedia_url",
    "transfermarkt_url",
    "image_url",
    "image_credit",
]

rows = [
    {
        "stadium_id": 171,
        "stadium_name": "Estádio Municipal de Famalicão",
        "capacity": 5186,
        "address": "Vila Nova de Famalicão, Portugal",
        "year_of_construction": 1952,
        "owner_raw": "Vila Nova de Famalicão Municipality",
        "ownership": "Public",
        "stadium_type": "Open",
        "surface": "Natural grass",
        "architect": "",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Est%C3%A1dio_Municipal_22_de_Junho",
        "transfermarkt_url": "https://www.transfermarkt.com/fc-famalicao/stadion/verein/3329",
        "image_url": "https://en.wikipedia.org/wiki/File:Blick_von_der_Gegentrib%C3%BCne_-_Est%C3%A1dio_Municipal_22_de_Junho.jpg",
        "image_credit": "",
    },
    {
        "stadium_id": 175,
        "stadium_name": "Estádio Pina Manique",
        "capacity": 2574,
        "address": "Parque de Monsanto, 1500-462 Lisboa, Portugal",
        "year_of_construction": 1954,
        "owner_raw": "",
        "ownership": "",
        "stadium_type": "Open",
        "surface": "Natural grass",
        "architect": "",
        "wikipedia_url": "",
        "transfermarkt_url": "https://www.transfermarkt.com/casa-pia-ac/stadion/verein/3268/stadion_id/5613",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 643,
        "stadium_name": "Luke Stadium",
        "capacity": 5000,
        "address": "Gračanica, Bosnia and Herzegovina",
        "year_of_construction": "",
        "owner_raw": "",
        "ownership": "",
        "stadium_type": "Open",
        "surface": "",
        "architect": "",
        "wikipedia_url": "",
        "transfermarkt_url": "https://www.transfermarkt.com/nk-bratstvo-gracanica/stadion/verein/3492",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 690,
        "stadium_name": "Stadion pod Vrmcem",
        "capacity": 425,
        "address": "Njegoševa bb, 85330 Kotor, Montenegro",
        "year_of_construction": 1922,
        "owner_raw": "Municipality of Kotor",
        "ownership": "Public",
        "stadium_type": "Open",
        "surface": "Natural grass",
        "architect": "",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Stadion_pod_Vrmcem",
        "transfermarkt_url": "https://www.transfermarkt.com/fk-bokelj/stadion/verein/4949",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 725,
        "stadium_name": "Tukums Stadium",
        "capacity": 350,
        "address": "Kuldīgas iela 74, LV-3104 Tukums, Latvia",
        "year_of_construction": "",
        "owner_raw": "",
        "ownership": "",
        "stadium_type": "Open",
        "surface": "Natural grass",
        "architect": "",
        "wikipedia_url": "",
        "transfermarkt_url": "https://www.transfermarkt.com/fk-tukums-2000/stadion/verein/28937",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 726,
        "stadium_name": "Grobiņas Stadion",
        "capacity": 200,
        "address": "Grobiņa, Latvia",
        "year_of_construction": "",
        "owner_raw": "",
        "ownership": "",
        "stadium_type": "Open",
        "surface": "",
        "architect": "",
        "wikipedia_url": "https://en.wikipedia.org/wiki/FK_Grobi%C5%86a",
        "transfermarkt_url": "",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 727,
        "stadium_name": "Ogres Sporta Komplekss",
        "capacity": 1250,
        "address": "Skolas iela 21, LV-5001 Ogre, Latvia",
        "year_of_construction": "",
        "owner_raw": "Ogre Municipality / Ogre Sports Centre",
        "ownership": "Public",
        "stadium_type": "Open",
        "surface": "Natural grass",
        "architect": "",
        "wikipedia_url": "",
        "transfermarkt_url": "https://www.transfermarkt.com/ogre-united/stadion/verein/107916",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 732,
        "stadium_name": "Cricova teren sintetic",
        "capacity": 0,
        "address": "Cricova, Moldova",
        "year_of_construction": "",
        "owner_raw": "",
        "ownership": "",
        "stadium_type": "Open",
        "surface": "Artificial turf",
        "architect": "",
        "wikipedia_url": "",
        "transfermarkt_url": "https://www.transfermarkt.com/politehnica-utm-shisinau/startseite/verein/90107",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 796,
        "stadium_name": "Ullevaal Stadion",
        "capacity": 27182,
        "address": "Sognsveien 75, Oslo, Norway",
        "year_of_construction": 1926,
        "owner_raw": "Football Association of Norway",
        "ownership": "Private",
        "stadium_type": "Open",
        "surface": "Natural grass",
        "architect": "",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Ullevaal_Stadion",
        "transfermarkt_url": "https://www.transfermarkt.com/norway/stadion/verein/3440",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 797,
        "stadium_name": "Bilino Polje",
        "capacity": 13812,
        "address": "Bulevar Kulina Bana bb, Zenica, Bosnia and Herzegovina",
        "year_of_construction": 1972,
        "owner_raw": "City of Zenica",
        "ownership": "Public",
        "stadium_type": "Open",
        "surface": "Hybrid grass",
        "architect": "",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Bilino_Polje_Stadium",
        "transfermarkt_url": "https://www.transfermarkt.com/nk-celik-zenica/stadion/verein/765",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 857,
        "stadium_name": "David Petriashvili Stadium",
        "capacity": 2130,
        "address": "Tbilisi, Georgia",
        "year_of_construction": 2015,
        "owner_raw": "Georgian Football Federation",
        "ownership": "Private",
        "stadium_type": "Open",
        "surface": "Natural grass",
        "architect": "",
        "wikipedia_url": "",
        "transfermarkt_url": "https://www.transfermarkt.com/fc-tskhinvali/stadion/verein/19090",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 861,
        "stadium_name": "Tskaltubo Central Stadium",
        "capacity": 12000,
        "address": "Tskaltubo, Georgia",
        "year_of_construction": "",
        "owner_raw": "",
        "ownership": "",
        "stadium_type": "Open",
        "surface": "",
        "architect": "",
        "wikipedia_url": "",
        "transfermarkt_url": "https://www.transfermarkt.com/fc-samgurali-tskaltubo/stadion/verein/29675",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 864,
        "stadium_name": "Nisporeni Central Stadium",
        "capacity": 5200,
        "address": "8 Great National Assembly Street, Nisporeni, Moldova",
        "year_of_construction": 2021,
        "owner_raw": "Nisporeni",
        "ownership": "Public",
        "stadium_type": "Open",
        "surface": "Grass",
        "architect": "",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Nisporeni_Central_Stadium",
        "transfermarkt_url": "https://www.transfermarkt.com/sporting-trestieni/stadion/verein/86958",
        "image_url": "https://commons.wikimedia.org/wiki/Category:Nisporeni_Central_Stadium",
        "image_credit": "",
    },
    {
        "stadium_id": 979,
        "stadium_name": "Nairi Stadium",
        "capacity": 6850,
        "address": "Yerevan, Armenia",
        "year_of_construction": 1960,
        "owner_raw": "FC Urartu",
        "ownership": "Private",
        "stadium_type": "Open",
        "surface": "Grass",
        "architect": "",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Nairi_Stadium",
        "transfermarkt_url": "",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 990,
        "stadium_name": "Ferizaj City Stadium",
        "capacity": 3000,
        "address": "Ferizaj, Kosovo",
        "year_of_construction": "",
        "owner_raw": "",
        "ownership": "",
        "stadium_type": "Open",
        "surface": "Artificial turf",
        "architect": "",
        "wikipedia_url": "https://en.wikipedia.org/wiki/FC_Ferizaj",
        "transfermarkt_url": "https://www.transfermarkt.com/kf-ferizaj/stadion/verein/29051",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 994,
        "stadium_name": "Sami Kelmendi Stadium",
        "capacity": 2500,
        "address": "Xhevdet Breznica, Lipjan, Kosovo",
        "year_of_construction": "",
        "owner_raw": "",
        "ownership": "",
        "stadium_type": "Open",
        "surface": "Artificial turf",
        "architect": "",
        "wikipedia_url": "",
        "transfermarkt_url": "https://www.transfermarkt.com/kf-arberia/stadion/verein/81007",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 1005,
        "stadium_name": "Tiberias Municipal Stadium",
        "capacity": 7554,
        "address": "Tiberias, Israel",
        "year_of_construction": "",
        "owner_raw": "Municipality of Tiberias",
        "ownership": "Public",
        "stadium_type": "Open",
        "surface": "Grass",
        "architect": "Moti Bodek",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Tiberias_Football_Stadium",
        "transfermarkt_url": "",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 1011,
        "stadium_name": "Bridge Meadow",
        "capacity": 2467,
        "address": "Bridge Meadow Lane, Sydney Rees Way, Haverfordwest, Pembrokeshire SA61 2EX, Wales",
        "year_of_construction": "",
        "owner_raw": "",
        "ownership": "",
        "stadium_type": "Open",
        "surface": "Natural grass",
        "architect": "",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Bridge_Meadow_Stadium",
        "transfermarkt_url": "https://www.transfermarkt.com/haverfordwest-county/stadion/verein/25232",
        "image_url": "",
        "image_credit": "",
    },
    {
        "stadium_id": 1013,
        "stadium_name": "Llanelian Road",
        "capacity": 3000,
        "address": "Llanelian Road, LL29 8UN Old Colwyn, Wales",
        "year_of_construction": 1984,
        "owner_raw": "Colwyn Bay F.C.",
        "ownership": "Private",
        "stadium_type": "Open",
        "surface": "Grass",
        "architect": "",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Llanelian_Road",
        "transfermarkt_url": "https://www.transfermarkt.com/colwyn-bay-fc/stadion/verein/22546",
        "image_url": "",
        "image_credit": "",
    },
]

path = Path("./italiastadiaapp/data/stadium_missing_data_import.csv")
with path.open("w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=columns)
    writer.writeheader()
    writer.writerows(rows)

path.as_posix()
