"""
Django settings for italianstadia project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

# In development, never let @cache_page serve a stale rendered page after a
# template/view edit. DummyCache is a no-op, so dev always renders fresh; prod
# (DEBUG=False) keeps the default in-memory LocMemCache.
if DEBUG:
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.dummy.DummyCache"}}

# Google AdSense publisher ID — set in Render env vars when account is approved.
# Empty string means no ads are rendered anywhere (safe default for dev/staging).
# Both vars must be set in Render env for ads to appear.
# GOOGLE_ADSENSE_CLIENT  e.g. ca-pub-1234567890123456
# GOOGLE_ADSENSE_SLOT    e.g. 1234567890  (from the AdSense "Ad units" dashboard)
GOOGLE_ADSENSE_CLIENT = os.environ.get("GOOGLE_ADSENSE_CLIENT", "")
GOOGLE_ADSENSE_SLOT   = os.environ.get("GOOGLE_ADSENSE_SLOT", "")

# MapTiler API key — set in Render env vars; never commit to git.
MAPTILER_API_KEY = os.environ.get("MAPTILER_API_KEY", "")

# Stripe — set STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET in Render env vars.
# STRIPE_MODE selects which key set is active:
#   "live" (default) → STRIPE_SECRET_KEY / STRIPE_WEBHOOK_SECRET
#   "test"           → STRIPE_TEST_SECRET_KEY / STRIPE_TEST_WEBHOOK_SECRET
# Set STRIPE_MODE=test on Render to test the full pay→download flow for free
# (test card 4242 4242 4242 4242), then set it back to live. No real charges.
STRIPE_MODE = os.environ.get("STRIPE_MODE", "live").lower()
if STRIPE_MODE == "test":
    STRIPE_SECRET_KEY     = os.environ.get("STRIPE_TEST_SECRET_KEY", "")
    STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_TEST_WEBHOOK_SECRET", "")
else:
    STRIPE_SECRET_KEY     = os.environ.get("STRIPE_SECRET_KEY", "")
    STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
STRIPE_PRICE_EXPORT    = os.environ.get("STRIPE_PRICE_EXPORT", "")
EXPORT_BASE_URL        = os.environ.get("EXPORT_BASE_URL", "http://localhost:8000")

# Email — set GMAIL_USER and GMAIL_APP_PASSWORD in Render env vars
EMAIL_BACKEND         = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST            = "smtp.gmail.com"
EMAIL_PORT            = 587
EMAIL_USE_TLS         = True
EMAIL_HOST_USER       = os.environ.get("GMAIL_USER", "")
EMAIL_HOST_PASSWORD   = os.environ.get("GMAIL_APP_PASSWORD", "")
DEFAULT_FROM_EMAIL    = os.environ.get("GMAIL_USER", "noreply@stadiumsofeurope.com")

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-dev-key"
)

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com",
    ".stadiumsofeurope.com",
]

# Render terminates TLS at its proxy and forwards X-Forwarded-Proto. Without
# this, request.scheme/is_secure() return "http" behind the proxy, so canonical
# tags, og:url and sitemap URLs would wrongly use http:// instead of https://.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'italiastadiaapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'italianstadia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'italiastadiaapp.context_processors.adsense',
            ],
        },
    },
]

WSGI_APPLICATION = 'italianstadia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=bool(os.getenv("DATABASE_URL")),
    )
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

