# Generated by Django 4.2.11 on 2024-06-02 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('year_of_construction', models.IntegerField()),
                ('average_attendance', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadia', to='italiastadiaapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founded', models.DateField()),
                ('tier', models.CharField(choices=[('Serie A', 'Serie A'), ('Serie B', 'Serie B'), ('Serie C', 'Serie C'), ('Serie D', 'Serie D')], max_length=20)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='italiastadiaapp.stadium')),
            ],
        ),
    ]
