# Generated by Django 4.2.11 on 2024-06-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('italiastadiaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='num_of_titles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Serie A'), (2, 'Serie B'), (3, 'Serie C'), (4, 'Serie D')]),
        ),
    ]
