# Generated by Django 4.2.11 on 2024-07-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('italiastadiaapp', '0002_team_manager_team_num_of_titles_alter_team_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='italiastadiaapp.city'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='average_attendance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to='italiastadiaapp.city'),
        ),
    ]
