# Generated by Django 4.2.11 on 2024-07-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('italiastadiaapp', '0003_team_city_alter_stadium_average_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='italiastadiaapp.city'),
        ),
    ]
