# Generated by Django 5.1.2 on 2024-11-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('italiastadiaapp', '0004_alter_team_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='average_attendance',
        ),
        migrations.AddField(
            model_name='team',
            name='average_attendance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
