# Generated by Django 5.1.2 on 2026-04-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0005_remove_stadium_average_attendance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadium",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stadium",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
