# Generated by Django 5.1.2 on 2026-05-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0006_stadium_latitude_stadium_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="wikipedia_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stadium",
            name="transfermarkt_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stadium",
            name="wikipedia_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="transfermarkt_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="wikipedia_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
