# Generated by Django 5.1.2 on 2026-05-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "italiastadiaapp",
            "0007_city_wikipedia_url_stadium_transfermarkt_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stadium",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stadium",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
