# Generated by Django 5.1.2 on 2026-05-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0008_stadium_description_stadium_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
