# Generated by Django 5.1.2 on 2026-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "italiastadiaapp",
            "0009_city_description_city_image_url_team_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="founded",
            field=models.DateField(blank=True, null=True),
        ),
    ]
