# Generated by Django 5.1.2 on 2026-05-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0010_alter_team_founded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stadium",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="year_of_construction",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
