# Generated by Django 5.1.2 on 2026-05-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "italiastadiaapp",
            "0011_alter_stadium_address_alter_stadium_capacity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="girone",
            field=models.CharField(
                blank=True,
                choices=[("A", "Girone A"), ("B", "Girone B"), ("C", "Girone C")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="tier",
            field=models.IntegerField(
                choices=[(1, "Serie A"), (2, "Serie B"), (3, "Serie C")]
            ),
        ),
    ]
