# Generated by Django 5.1.2 on 2026-05-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0012_team_girone_alter_team_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadium",
            name="owner_raw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stadium",
            name="ownership",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("PRIVATE", "Private"),
                    ("MIXED", "Mixed"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
    ]
