# Generated by Django 5.1.2 on 2026-05-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0013_stadium_owner_raw_stadium_ownership"),
    ]

    operations = [
        migrations.CreateModel(
            name="StadiumDevelopment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New Stadium"),
                            ("REDEVELOPMENT", "Redevelopment"),
                            ("EXPANSION", "Expansion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("APPROVED", "Approved"),
                            ("UNDER_CONSTRUCTION", "Under Construction"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("future_capacity", models.IntegerField(blank=True, null=True)),
                ("estimated_opening", models.IntegerField(blank=True, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("architect", models.CharField(blank=True, max_length=255)),
                ("developer", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "stadium",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="italiastadiaapp.stadium",
                    ),
                ),
            ],
        ),
    ]
