# Generated by Django 5.1.2 on 2026-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0014_stadiumdevelopment"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadiumdevelopment",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stadiumdevelopment",
            name="webpage_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
