# Generated by Django 5.1.2 on 2026-05-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0015_stadiumdevelopment_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stadiumdevelopment",
            name="webpage_url",
        ),
        migrations.AddField(
            model_name="team",
            name="under_development_stadium",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="future_tenants",
                to="italiastadiaapp.stadiumdevelopment",
            ),
        ),
    ]
