# Generated by Django 5.1.2 on 2026-05-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0016_remove_stadiumdevelopment_webpage_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="image_credit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stadium",
            name="image_credit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stadiumdevelopment",
            name="image_credit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="image_credit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
