# Generated by Django 5.1.2 on 2026-05-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0017_city_image_credit_stadium_image_credit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
