# Generated by Django 5.1.2 on 2026-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0018_alter_city_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="image_credit",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="image_credit",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="image_credit",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="image_credit",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
