# Generated by Django 5.1.2 on 2026-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "italiastadiaapp",
            "0019_alter_city_image_credit_alter_city_image_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="city",
            name="wikipedia_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="transfermarkt_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="wikipedia_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="architect",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="developer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="source_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="manager",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="team",
            name="transfermarkt_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="wikipedia_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
