# Generated by Django 5.1.2 on 2026-05-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0023_alter_country_code_alter_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="population",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="average_attendance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="tier",
            field=models.IntegerField(
                choices=[
                    (1, "First Division"),
                    (2, "Second Division"),
                    (3, "Third Division"),
                ]
            ),
        ),
    ]
