# Generated by Django 6.0.5 on 2026-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0024_alter_city_population_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadium",
            name="extra_images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
