# Generated by Django 5.1.2 on 2026-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0025_stadium_extra_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
