# Generated by Django 5.1.2 on 2026-06-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0026_alter_stadiumdevelopment_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="uefa_rank",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
