# Generated by Django 5.1.2 on 2026-06-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0027_country_uefa_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
