# Generated by Django 5.1.2 on 2026-06-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0028_alter_city_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="num_of_titles",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
