# Generated by Django 6.0.5 on 2026-06-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0034_fix_allsvenskan_unknown_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="uefa_coefficient",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
