# Generated by Django 6.0.5 on 2026-06-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0037_seed_all_country_uefa_ranks"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastRefresh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ran_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Last Refresh",
                "verbose_name_plural": "Last Refresh",
            },
        ),
    ]
