# Generated by Django 5.1.2 on 2026-06-13 15:03

from django.db import migrations, models


def backfill_italian_country(apps, schema_editor):
    StadiumDevelopment = apps.get_model("italiastadiaapp", "StadiumDevelopment")
    StadiumDevelopment.objects.filter(pk__lte=10).update(country="Italy")


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0038_add_lastrefresh"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadiumdevelopment",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(backfill_italian_country, migrations.RunPython.noop),
    ]
