# Generated by Django 5.1.2 on 2026-06-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0039_add_country_to_stadium_development"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="league",
            unique_together={("name", "country")},
        ),
    ]
