# Generated by Django 5.1.2 on 2026-06-13 18:07

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Stadium = apps.get_model("italiastadiaapp", "Stadium")
    seen = {}
    for s in Stadium.objects.order_by("id"):
        if s.slug:
            seen[s.slug] = True
            continue
        base = slugify(s.name) or f"stadium-{s.id}"
        slug, n = base, 2
        while slug in seen:
            slug = f"{base}-{n}"
            n += 1
        seen[slug] = True
        s.slug = slug
        s.save(update_fields=["slug"])


def fix_pg_indexes(apps, schema_editor):
    """
    On PostgreSQL only: ensure the unique constraint and varchar_pattern_ops
    index on stadium.slug exist, using IF NOT EXISTS so this is safe even if
    a previous failed deploy already created them.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as c:
        c.execute(
            "DO $$ BEGIN "
            "IF NOT EXISTS (SELECT 1 FROM pg_constraint "
            "WHERE conname = 'italiastadiaapp_stadium_slug_b1ce6737_uniq') THEN "
            "ALTER TABLE italiastadiaapp_stadium "
            "ADD CONSTRAINT italiastadiaapp_stadium_slug_b1ce6737_uniq UNIQUE (slug); "
            "END IF; END $$;"
        )
        c.execute(
            "CREATE INDEX IF NOT EXISTS italiastadiaapp_stadium_slug_b1ce6737_like "
            "ON italiastadiaapp_stadium (slug varchar_pattern_ops);"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0040_alter_league_name_alter_league_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadium",
            name="architect",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # Add slug without unique=True first so existing rows default to '' without conflict.
        migrations.AddField(
            model_name="stadium",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=False),
        ),
        migrations.AddField(
            model_name="stadium",
            name="stadium_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("RETRACTABLE", "Retractable roof"),
                    ("INDOOR", "Indoor"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stadium",
            name="surface",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GRASS", "Grass"),
                    ("ARTIFICIAL", "Artificial"),
                    ("HYBRID", "Hybrid"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stadium",
            name="tournaments",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        # On PostgreSQL, AlterField would blindly re-create the _like index that
        # AddField(unique=False) already created → "relation already exists".
        # fix_pg_indexes creates both idempotently; AlterField handles SQLite/other.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(fix_pg_indexes, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="stadium",
                    name="slug",
                    field=models.SlugField(blank=True, max_length=255, unique=True),
                ),
            ],
        ),
    ]
