# Generated by Django 5.1.2 on 2026-06-13 18:07

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Stadium = apps.get_model("italiastadiaapp", "Stadium")
    seen = {}
    for s in Stadium.objects.order_by("id"):
        base = slugify(s.name) or f"stadium-{s.id}"
        slug, n = base, 2
        while slug in seen:
            slug = f"{base}-{n}"
            n += 1
        seen[slug] = True
        s.slug = slug
        s.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0040_alter_league_name_alter_league_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadium",
            name="architect",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # Add slug WITHOUT unique=True first so existing rows default to '' without conflict
        migrations.AddField(
            model_name="stadium",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=False),
        ),
        migrations.AddField(
            model_name="stadium",
            name="stadium_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("RETRACTABLE", "Retractable roof"),
                    ("INDOOR", "Indoor"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stadium",
            name="surface",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GRASS", "Grass"),
                    ("ARTIFICIAL", "Artificial"),
                    ("HYBRID", "Hybrid"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stadium",
            name="tournaments",
            field=models.JSONField(blank=True, default=list),
        ),
        # Backfill unique slugs before adding the unique constraint
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        # Now enforce uniqueness
        migrations.AlterField(
            model_name="stadium",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
