# Generated by Django 5.1.2 on 2026-06-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0041_add_stadium_metadata_and_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadiumdevelopment",
            name="tournaments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
