# Generated by Django 5.1.2 on 2026-06-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0042_stadiumdevelopment_tournaments"),
    ]

    operations = [
        # Make tier nullable first so SQLite's _remake_table doesn't choke on
        # existing rows that already have tier=NULL (national team records).
        migrations.AlterField(
            model_name="team",
            name="tier",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "First Division"),
                    (2, "Second Division"),
                    (3, "Third Division"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="is_national",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
