# Generated by Django 5.1.2 on 2026-06-14 20:27

from django.db import migrations, models
from django.utils.text import slugify


def backfill_team_slugs(apps, schema_editor):
    Team = apps.get_model("italiastadiaapp", "Team")
    for team in Team.objects.order_by("pk"):
        if team.slug:
            continue
        base = slugify(team.name) or f"team-{team.pk}"
        slug = base
        n = 2
        while Team.objects.filter(slug=slug).exclude(pk=team.pk).exists():
            slug = f"{base}-{n}"
            n += 1
        team.slug = slug
        team.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0044_mark_national_teams"),
    ]

    operations = [
        # Add without unique so SQLite doesn't reject blank rows during table copy
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_team_slugs, migrations.RunPython.noop),
        # Now all slugs are filled — safe to enforce unique
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
