# Generated by Django 5.1.2 on 2026-06-14 20:27

from django.db import migrations, models
from django.utils.text import slugify


def apply_everything(apps, schema_editor):
    """
    Fully idempotent: add column, backfill slugs, create unique index.
    Uses IF NOT EXISTS / IF EXISTS throughout so concurrent migrate processes
    (Render multi-worker) and retries after partial failures are all safe.
    """
    conn = schema_editor.connection
    vendor = conn.vendor
    Team = apps.get_model("italiastadiaapp", "Team")

    with conn.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute(
                "ALTER TABLE italiastadiaapp_team "
                "ADD COLUMN IF NOT EXISTS slug varchar(255) NOT NULL DEFAULT ''"
            )
        elif vendor == "sqlite":
            cursor.execute("PRAGMA table_info(italiastadiaapp_team)")
            if "slug" not in [row[1] for row in cursor.fetchall()]:
                cursor.execute(
                    "ALTER TABLE italiastadiaapp_team "
                    "ADD COLUMN slug varchar(255) NOT NULL DEFAULT ''"
                )

    # 2. Backfill slugs (already skips teams that have one)
    for team in Team.objects.order_by("pk"):
        if team.slug:
            continue
        base = slugify(team.name) or f"team-{team.pk}"
        slug = base
        n = 2
        while Team.objects.filter(slug=slug).exclude(pk=team.pk).exists():
            slug = f"{base}-{n}"
            n += 1
        team.slug = slug
        team.save(update_fields=["slug"])

    # 3. Create unique index idempotently
    #    DROP any prior artifacts (constraint-backed or standalone), then
    #    CREATE IF NOT EXISTS — safe even under concurrent migrate processes.
    with conn.cursor() as cursor:
        if vendor == "postgresql":
            # Drop constraint if it exists (also drops its backing index)
            cursor.execute(
                "ALTER TABLE italiastadiaapp_team "
                "DROP CONSTRAINT IF EXISTS italiastadiaapp_team_slug_f547d06f_uniq"
            )
            # Drop standalone indexes in case they exist without a constraint
            cursor.execute(
                "DROP INDEX IF EXISTS italiastadiaapp_team_slug_f547d06f_uniq"
            )
            cursor.execute(
                "DROP INDEX IF EXISTS italiastadiaapp_team_slug_f547d06f_like"
            )
            # CREATE IF NOT EXISTS — concurrent processes skip silently
            cursor.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS "
                "italiastadiaapp_team_slug_f547d06f_uniq "
                "ON italiastadiaapp_team (slug)"
            )
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS "
                "italiastadiaapp_team_slug_f547d06f_like "
                "ON italiastadiaapp_team (slug varchar_pattern_ops)"
            )
        elif vendor == "sqlite":
            cursor.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS "
                "italiastadiaapp_team_slug_uniq ON italiastadiaapp_team (slug)"
            )


class Migration(migrations.Migration):
    atomic = False  # Each statement commits independently — safe for retries

    dependencies = [
        ("italiastadiaapp", "0044_mark_national_teams"),
    ]

    operations = [
        # State-only: update Django's ORM state without running DDL
        # (apply_everything handles all DDL idempotently)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="team",
                    name="slug",
                    field=models.SlugField(blank=True, max_length=255),
                ),
            ],
        ),
        migrations.RunPython(apply_everything, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="team",
                    name="slug",
                    field=models.SlugField(blank=True, max_length=255, unique=True),
                ),
            ],
        ),
    ]
