# Generated by Django 5.1.2 on 2026-06-15 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0045_team_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("stripe_session", models.CharField(db_index=True, max_length=255)),
                ("filters_json", models.TextField()),
                ("paid", models.BooleanField(default=False)),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
    ]
