# Generated by Django 5.1.2 on 2026-06-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0046_export_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadium",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="Protect manual corrections — the scraper skips locked stadiums.",
            ),
        ),
    ]
