# Generated by Django 5.1.2 on 2026-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0073_adhoc_team_stadium_fixes"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="population",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "New Stadium"),
                    ("REDEVELOPMENT", "Redevelopment"),
                    ("EXPANSION", "Expansion"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="stadiumdevelopment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PLANNING", "Planning"),
                    ("APPROVED", "Approved"),
                    ("UNDER_CONSTRUCTION", "Under Construction"),
                    ("ON_HOLD", "On Hold"),
                    ("COMPLETED", "Completed"),
                ],
                max_length=30,
            ),
        ),
    ]
