# Generated by Django 5.1.2 on 2026-08-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0076_team_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="season",
            field=models.CharField(blank=True, default="2025/26", max_length=9),
        ),
    ]
