# Generated by Django 5.1.2 on 2026-08-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0077_league_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
