# Generated by Django 5.1.2 on 2026-08-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0078_league_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="stadium",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="italiastadiaapp.stadium",
            ),
        ),
    ]
