# Generated by Django 5.1.2 on 2026-08-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0079_alter_team_stadium"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="crest_file",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
