# Generated by Django 5.1.2 on 2026-08-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0080_team_crest_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="tier",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "First Division"),
                    (2, "Second Division"),
                    (3, "Third Division"),
                    (4, "Fourth Division"),
                ],
                null=True,
            ),
        ),
    ]
