# Generated by Django 5.1.2 on 2026-08-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0081_alter_team_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="european_competition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UCL", "UEFA Champions League"),
                    ("UEL", "UEFA Europa League"),
                    ("UECL", "UEFA Conference League"),
                ],
                db_index=True,
                default="",
                max_length=8,
            ),
        ),
    ]
