# Generated by Django 5.1.2 on 2026-09-04 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("italiastadiaapp", "0082_team_european_competition"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="uefa_stadium",
            field=models.ForeignKey(
                blank=True,
                help_text="Ground used for European home matches, if not the usual one.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uefa_tenants",
                to="italiastadiaapp.stadium",
            ),
        ),
    ]
